### ISSUE TITLE
[DOCS]: Làm sao mình có thể di chuyển toàn bộ files của thư viện ra thư mục root?

### ISSUE THREAD

**Issue by nguyenthanhan201** [techmely/essential-packages#258]
### Describe the need

<img width="787" alt="Screenshot 2023-12-24 at 18 40 11" src="https://github.com/techmely/essential-packages/assets/80932055/4e239ce1-b0d8-4e2e-8f9f-66a64ff29b16">
<img width="764" alt="Screenshot 2023-12-24 at 18 40 41" src="https://github.com/techmely/essential-packages/assets/80932055/ed9aa6f7-54fd-48f7-b9c7-1abf025ad644">
của mình khi build ra các files luôn nằm trong folder dist, làm sao mình có thể di chuyển files ra ngoài root (như hình 1)?
Cảm ơn vì đã đọc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harrytran998** [comment]
Cảm ơn bạn đã quan tâm. Bạn xem phần https://github.com/techmely/essential-packages/blob/main/scripts/publishPkg.mjs nhé. Idea là khi build ra `dist` folder --> copy 1 file `package.json` vào đó --> move `executor`(terminal) vào `dist` --> Nó sẽ publish nguyên cả folder `dist`. 

Nếu có gì chưa hiểu thì có thể ping mình ở FB nhé ✌🏻

**Comment by nguyenthanhan201** [comment]
Cảm ơn @harrytran998 đã hỗ trợ mình, mình sẽ làm thử xem sao

**Comment by nguyenthanhan201** [comment]
khi mà mình chạy npm run publish thì nó bị lỗi này
